Bring oconfigure to 0.1.5.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,7 +1,7 @@
 #! /bin/sh
 #
 # Copyright (c) 2014, 2015, 2016 Ingo Schwarze <schwarze@openbsd.org>
-# Copyright (c) 2017 Kristaps Dzonsons <kristaps@bsd.lv>
+# Copyright (c) 2017, 2018 Kristaps Dzonsons <kristaps@bsd.lv>
 #
 # Permission to use, copy, modify, and distribute this software for any
 # purpose with or without fee is hereby granted, provided that the above
@@ -15,7 +15,7 @@
 # ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 
-OCONFIGURE_VERSION="0.1.3"
+OCONFIGURE_VERSION="0.1.5"
 
 #
 # This script outputs two files: config.h and Makefile.configure.
@@ -132,6 +132,7 @@ done
 #----------------------------------------------------------------------
 
 HAVE_ARC4RANDOM=
+HAVE_B64_NTOP=
 HAVE_CAPSICUM=
 HAVE_ERR=
 HAVE_EXPLICIT_BZERO=
@@ -201,42 +202,68 @@ ismanual() {
 # CFLAGS, additional LIBS.
 
 singletest() {
+	extralib=""
 	cat 1>&3 << __HEREDOC__
 ${1}: testing...
 ${COMP} -DTEST_${2} ${3} -o test-${1} tests.c ${4}
 __HEREDOC__
-
 	if ${COMP} -DTEST_${2} ${3} -o "test-${1}" tests.c ${4} 1>&3 2>&3; then
 		echo "${1}: ${CC} succeeded" 1>&3
-	else
-		echo "${1}: ${CC} failed with $?" 1>&3
-		echo 1>&3
-		return 1
+	else 
+		if [ -n "${5}" ] ; then
+			echo "${1}: ${CC} failed with $? (retrying)" 1>&3
+			cat 1>&3 << __HEREDOC__
+${1}: testing...
+${COMP} -DTEST_${2} ${3} -o test-${1} tests.c ${5}
+__HEREDOC__
+			if ${COMP} -DTEST_${2} ${3} -o "test-${1}" tests.c ${5} 1>&3 2>&3; then
+				echo "${1}: ${CC} succeeded" 1>&3
+				extralib="(with ${5})"
+			else 
+				echo "${1}: ${CC} failed with $?" 1>&3
+				echo 1>&3
+				return 1
+			fi
+		else
+			echo "${1}: ${CC} failed with $?" 1>&3
+			echo 1>&3
+			return 1
+		fi
 	fi
 
-	if ./test-${1} 1>&3 2>&3; then
-		echo "${1}: yes" 1>&2
-		echo "${1}: yes" 1>&3
-		echo 1>&3
-		eval HAVE_${2}=1
-		rm "test-${1}"
-		return 0
-	else
-		echo "${1}: execution failed with $?" 1>&3
-		echo 1>&3
-		rm "test-${1}"
-		return 1
-	fi
+	echo "${1}: yes ${extralib}" 1>&2
+	echo "${1}: yes ${extralib}" 1>&3
+	echo 1>&3
+	eval HAVE_${2}=1
+	rm "test-${1}"
+	return 0
+
+	# Don't actually run the test: none of our tests check for
+	# run-time behaviour.
+	# if ./test-${1} 1>&3 2>&3; then
+	# 	echo "${1}: yes" 1>&2
+	# 	echo "${1}: yes" 1>&3
+	# 	echo 1>&3
+	# 	eval HAVE_${2}=1
+	# 	rm "test-${1}"
+	# 	return 0
+	# else
+	# 	echo "${1}: execution failed with $?" 1>&3
+	# 	echo 1>&3
+	# 	rm "test-${1}"
+	# 	return 1
+	# fi
 }
 
 # Run a complete autoconfiguration test, including the check for
 # a manual override and disabling the feature on failure.
-# Arguments: lower case name, upper case name, additional CFLAGS
+# Arguments: lower case name, upper case name, additional CFLAGS, 
+# additional LDADD, alternative LDADD.
 
 runtest() {
 	eval _manual=\${HAVE_${2}}
 	ismanual "${1}" "${2}" "${_manual}" && return 0
-	singletest "${1}" "${2}" "${3}" "${4}" "${test}" && return 0
+	singletest "${1}" "${2}" "${3}" "${4}" "${5}" && return 0
 	echo "${1}: no" 1>&2
 	eval HAVE_${2}=0
 	return 1
@@ -247,9 +274,17 @@ runtest() {
 # All of your tests must be defined here.
 # Please sort as the HAVE_xxxx values were defined.
 # You WANT to change this.
+# It consists of the following columns:
+#    runtest
+#    (1) test file
+#    (2) macro to set
+#    (3) argument to cc *before* -o
+#    (4) argument to cc *after* 
+#    (5) alternative argument to cc *after* 
 #----------------------------------------------------------------------
 
 runtest arc4random	ARC4RANDOM			  || true
+runtest b64_ntop	B64_NTOP "" "" "-lresolv"	  || true
 runtest capsicum	CAPSICUM			  || true
 runtest err		ERR				  || true
 runtest explicit_bzero	EXPLICIT_BZERO			  || true
@@ -331,6 +366,7 @@ __HEREDOC__
 
 cat << __HEREDOC__
 #define HAVE_ARC4RANDOM ${HAVE_ARC4RANDOM}
+#define HAVE_B64_NTOP ${HAVE_B64_NTOP}
 #define HAVE_CAPSICUM ${HAVE_CAPSICUM}
 #define HAVE_ERR ${HAVE_ERR}
 #define HAVE_EXPLICIT_BZERO ${HAVE_EXPLICIT_BZERO}
@@ -401,6 +437,11 @@ if [ ${HAVE_SECCOMP_FILTER} -eq 1 ]; then
 			echo "#define SECCOMP_AUDIT_ARCH AUDIT_ARCH_ARM"
 			;;
 	esac
+fi
+
+if [ ${HAVE_B64_NTOP} -eq 0 ]; then
+	echo "extern int b64_ntop(unsigned char const *, size_t, char *, size_t);";
+	echo "extern int b64_pton(char const *, unsigned char *, size_t);"
 fi
 
 if [ ${HAVE_EXPLICIT_BZERO} -eq 0 ]; then
